// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: online.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "online.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace online {

namespace {

const ::google::protobuf::Descriptor* OnlineSheet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OnlineSheet_reflection_ = NULL;
const ::google::protobuf::Descriptor* OnlinePerson_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OnlinePerson_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_online_2eproto() {
  protobuf_AddDesc_online_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "online.proto");
  GOOGLE_CHECK(file != NULL);
  OnlineSheet_descriptor_ = file->message_type(0);
  static const int OnlineSheet_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineSheet, sheets_),
  };
  OnlineSheet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OnlineSheet_descriptor_,
      OnlineSheet::default_instance_,
      OnlineSheet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineSheet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineSheet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OnlineSheet));
  OnlinePerson_descriptor_ = file->message_type(1);
  static const int OnlinePerson_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlinePerson, name_),
  };
  OnlinePerson_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OnlinePerson_descriptor_,
      OnlinePerson::default_instance_,
      OnlinePerson_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlinePerson, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlinePerson, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OnlinePerson));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_online_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OnlineSheet_descriptor_, &OnlineSheet::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OnlinePerson_descriptor_, &OnlinePerson::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_online_2eproto() {
  delete OnlineSheet::default_instance_;
  delete OnlineSheet_reflection_;
  delete OnlinePerson::default_instance_;
  delete OnlinePerson_reflection_;
}

void protobuf_AddDesc_online_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014online.proto\022\006online\"3\n\013OnlineSheet\022$\n"
    "\006sheets\030\001 \003(\0132\024.online.OnlinePerson\"\034\n\014O"
    "nlinePerson\022\014\n\004name\030\001 \002(\t", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "online.proto", &protobuf_RegisterTypes);
  OnlineSheet::default_instance_ = new OnlineSheet();
  OnlinePerson::default_instance_ = new OnlinePerson();
  OnlineSheet::default_instance_->InitAsDefaultInstance();
  OnlinePerson::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_online_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_online_2eproto {
  StaticDescriptorInitializer_online_2eproto() {
    protobuf_AddDesc_online_2eproto();
  }
} static_descriptor_initializer_online_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int OnlineSheet::kSheetsFieldNumber;
#endif  // !_MSC_VER

OnlineSheet::OnlineSheet()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:online.OnlineSheet)
}

void OnlineSheet::InitAsDefaultInstance() {
}

OnlineSheet::OnlineSheet(const OnlineSheet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:online.OnlineSheet)
}

void OnlineSheet::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OnlineSheet::~OnlineSheet() {
  // @@protoc_insertion_point(destructor:online.OnlineSheet)
  SharedDtor();
}

void OnlineSheet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void OnlineSheet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OnlineSheet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OnlineSheet_descriptor_;
}

const OnlineSheet& OnlineSheet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_online_2eproto();
  return *default_instance_;
}

OnlineSheet* OnlineSheet::default_instance_ = NULL;

OnlineSheet* OnlineSheet::New() const {
  return new OnlineSheet;
}

void OnlineSheet::Clear() {
  sheets_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OnlineSheet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:online.OnlineSheet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .online.OnlinePerson sheets = 1;
      case 1: {
        if (tag == 10) {
         parse_sheets:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_sheets()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_sheets;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:online.OnlineSheet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:online.OnlineSheet)
  return false;
#undef DO_
}

void OnlineSheet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:online.OnlineSheet)
  // repeated .online.OnlinePerson sheets = 1;
  for (int i = 0; i < this->sheets_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->sheets(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:online.OnlineSheet)
}

::google::protobuf::uint8* OnlineSheet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:online.OnlineSheet)
  // repeated .online.OnlinePerson sheets = 1;
  for (int i = 0; i < this->sheets_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->sheets(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:online.OnlineSheet)
  return target;
}

int OnlineSheet::ByteSize() const {
  int total_size = 0;

  // repeated .online.OnlinePerson sheets = 1;
  total_size += 1 * this->sheets_size();
  for (int i = 0; i < this->sheets_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->sheets(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OnlineSheet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OnlineSheet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OnlineSheet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OnlineSheet::MergeFrom(const OnlineSheet& from) {
  GOOGLE_CHECK_NE(&from, this);
  sheets_.MergeFrom(from.sheets_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OnlineSheet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OnlineSheet::CopyFrom(const OnlineSheet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnlineSheet::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->sheets())) return false;
  return true;
}

void OnlineSheet::Swap(OnlineSheet* other) {
  if (other != this) {
    sheets_.Swap(&other->sheets_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OnlineSheet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OnlineSheet_descriptor_;
  metadata.reflection = OnlineSheet_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int OnlinePerson::kNameFieldNumber;
#endif  // !_MSC_VER

OnlinePerson::OnlinePerson()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:online.OnlinePerson)
}

void OnlinePerson::InitAsDefaultInstance() {
}

OnlinePerson::OnlinePerson(const OnlinePerson& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:online.OnlinePerson)
}

void OnlinePerson::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OnlinePerson::~OnlinePerson() {
  // @@protoc_insertion_point(destructor:online.OnlinePerson)
  SharedDtor();
}

void OnlinePerson::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void OnlinePerson::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OnlinePerson::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OnlinePerson_descriptor_;
}

const OnlinePerson& OnlinePerson::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_online_2eproto();
  return *default_instance_;
}

OnlinePerson* OnlinePerson::default_instance_ = NULL;

OnlinePerson* OnlinePerson::New() const {
  return new OnlinePerson;
}

void OnlinePerson::Clear() {
  if (has_name()) {
    if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      name_->clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OnlinePerson::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:online.OnlinePerson)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:online.OnlinePerson)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:online.OnlinePerson)
  return false;
#undef DO_
}

void OnlinePerson::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:online.OnlinePerson)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:online.OnlinePerson)
}

::google::protobuf::uint8* OnlinePerson::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:online.OnlinePerson)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:online.OnlinePerson)
  return target;
}

int OnlinePerson::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OnlinePerson::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OnlinePerson* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OnlinePerson*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OnlinePerson::MergeFrom(const OnlinePerson& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OnlinePerson::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OnlinePerson::CopyFrom(const OnlinePerson& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnlinePerson::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void OnlinePerson::Swap(OnlinePerson* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OnlinePerson::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OnlinePerson_descriptor_;
  metadata.reflection = OnlinePerson_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace online

// @@protoc_insertion_point(global_scope)
