// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: online.proto

#ifndef PROTOBUF_online_2eproto__INCLUDED
#define PROTOBUF_online_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace online {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_online_2eproto();
void protobuf_AssignDesc_online_2eproto();
void protobuf_ShutdownFile_online_2eproto();

class OnlineSheet;
class OnlinePerson;

// ===================================================================

class OnlineSheet : public ::google::protobuf::Message {
 public:
  OnlineSheet();
  virtual ~OnlineSheet();

  OnlineSheet(const OnlineSheet& from);

  inline OnlineSheet& operator=(const OnlineSheet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnlineSheet& default_instance();

  void Swap(OnlineSheet* other);

  // implements Message ----------------------------------------------

  OnlineSheet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnlineSheet& from);
  void MergeFrom(const OnlineSheet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .online.OnlinePerson sheets = 1;
  inline int sheets_size() const;
  inline void clear_sheets();
  static const int kSheetsFieldNumber = 1;
  inline const ::online::OnlinePerson& sheets(int index) const;
  inline ::online::OnlinePerson* mutable_sheets(int index);
  inline ::online::OnlinePerson* add_sheets();
  inline const ::google::protobuf::RepeatedPtrField< ::online::OnlinePerson >&
      sheets() const;
  inline ::google::protobuf::RepeatedPtrField< ::online::OnlinePerson >*
      mutable_sheets();

  // @@protoc_insertion_point(class_scope:online.OnlineSheet)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::online::OnlinePerson > sheets_;
  friend void  protobuf_AddDesc_online_2eproto();
  friend void protobuf_AssignDesc_online_2eproto();
  friend void protobuf_ShutdownFile_online_2eproto();

  void InitAsDefaultInstance();
  static OnlineSheet* default_instance_;
};
// -------------------------------------------------------------------

class OnlinePerson : public ::google::protobuf::Message {
 public:
  OnlinePerson();
  virtual ~OnlinePerson();

  OnlinePerson(const OnlinePerson& from);

  inline OnlinePerson& operator=(const OnlinePerson& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnlinePerson& default_instance();

  void Swap(OnlinePerson* other);

  // implements Message ----------------------------------------------

  OnlinePerson* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnlinePerson& from);
  void MergeFrom(const OnlinePerson& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:online.OnlinePerson)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  friend void  protobuf_AddDesc_online_2eproto();
  friend void protobuf_AssignDesc_online_2eproto();
  friend void protobuf_ShutdownFile_online_2eproto();

  void InitAsDefaultInstance();
  static OnlinePerson* default_instance_;
};
// ===================================================================


// ===================================================================

// OnlineSheet

// repeated .online.OnlinePerson sheets = 1;
inline int OnlineSheet::sheets_size() const {
  return sheets_.size();
}
inline void OnlineSheet::clear_sheets() {
  sheets_.Clear();
}
inline const ::online::OnlinePerson& OnlineSheet::sheets(int index) const {
  // @@protoc_insertion_point(field_get:online.OnlineSheet.sheets)
  return sheets_.Get(index);
}
inline ::online::OnlinePerson* OnlineSheet::mutable_sheets(int index) {
  // @@protoc_insertion_point(field_mutable:online.OnlineSheet.sheets)
  return sheets_.Mutable(index);
}
inline ::online::OnlinePerson* OnlineSheet::add_sheets() {
  // @@protoc_insertion_point(field_add:online.OnlineSheet.sheets)
  return sheets_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::online::OnlinePerson >&
OnlineSheet::sheets() const {
  // @@protoc_insertion_point(field_list:online.OnlineSheet.sheets)
  return sheets_;
}
inline ::google::protobuf::RepeatedPtrField< ::online::OnlinePerson >*
OnlineSheet::mutable_sheets() {
  // @@protoc_insertion_point(field_mutable_list:online.OnlineSheet.sheets)
  return &sheets_;
}

// -------------------------------------------------------------------

// OnlinePerson

// required string name = 1;
inline bool OnlinePerson::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OnlinePerson::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OnlinePerson::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OnlinePerson::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& OnlinePerson::name() const {
  // @@protoc_insertion_point(field_get:online.OnlinePerson.name)
  return *name_;
}
inline void OnlinePerson::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:online.OnlinePerson.name)
}
inline void OnlinePerson::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:online.OnlinePerson.name)
}
inline void OnlinePerson::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:online.OnlinePerson.name)
}
inline ::std::string* OnlinePerson::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:online.OnlinePerson.name)
  return name_;
}
inline ::std::string* OnlinePerson::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OnlinePerson::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:online.OnlinePerson.name)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace online

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_online_2eproto__INCLUDED
